### ISSUE TITLE
Fix `FileModificationWatcherThreadTest ` Travis unreliability

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1112]
There's a reliability issue when running our `FileModificationWatcherThreadTest` tests on Travis, which results in this strange call-stack:
```
org.bladerunnerjs.memoization.FileModificationWatcherThreadTest > usingTheRealWatchServiceDetectsFileNestedChanges FAILED
    java.lang.NoClassDefFoundError: Could not initialize class sun.nio.fs.LinuxWatchService
        at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at org.bladerunnerjs.memoization.DefaultWatchKeyService.<init>(DefaultWatchKeyService.java:27)
        at org.bladerunnerjs.memoization.WatchKeyServiceFactory.createWatchService(WatchKeyServiceFactory.java:16)
        at org.bladerunnerjs.memoization.FileModificationWatcherThread.init(FileModificationWatcherThread.java:64)
        at org.bladerunnerjs.memoization.FileModificationWatcherThreadTest.usingTheRealWatchServiceDetectsFileNestedChanges(FileModificationWatcherThreadTest.java:223)
org.bladerunnerjs.memoization.FileModificationWatcherThreadTest > usingTheRealWatchServiceDetectsFileChanges FAILED
    java.lang.NoClassDefFoundError: Could not initialize class sun.nio.fs.LinuxWatchService
        at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at org.bladerunnerjs.memoization.DefaultWatchKeyService.<init>(DefaultWatchKeyService.java:27)
        at org.bladerunnerjs.memoization.WatchKeyServiceFactory.createWatchService(WatchKeyServiceFactory.java:16)
        at org.bladerunnerjs.memoization.FileModificationWatcherThread.init(FileModificationWatcherThread.java:64)
        at org.bladerunnerjs.memoization.FileModificationWatcherThreadTest.usingTheRealWatchServiceDetectsFileChanges(FileModificationWatcherThreadTest.java:210)
```

This is weird because a `java.lang.NoClassDefFoundError: Could not initialize class XXX` normally means that [there was a static initialization error while initializing a class](http://stackoverflow.com/questions/7325579/java-lang-noclassdeffounderror-could-not-initialize-class-xxx), yet it's a Sun class in this case. It's also weird since it doesn't happen everytime. The only static member of `LinuxWatchService` is an `Unsafe` class, used for unsafe operations ([see here](http://cr.openjdk.java.net/~alanb/7006126/webrev.00/raw_files/new/src/solaris/classes/sun/nio/fs/LinuxWatchService.java)).

I can't find anything on-line about this bug, and I've not yet seen it occur locally. If anybody can replicate they should debug, otherwise we might want to add lines in to give us more information for when it happens again.

**Comment by andyberry88** [comment]
We've not seen this unreliability for a while so I'm going to close this. We can reopen if it comes back.
