### ISSUE TITLE
brjs test-integration command shows a stack trace when path arg is missing.

### ISSUE THREAD

**Issue by bit-shifter** [BladeRunnerJS/brjs#1129]
The command informs the user that the given args are invalid, but provides no usage detail to help them to correct the problem:

Console output:

```
Error:
  Invalid arguments provided.

Stack Trace:
org.bladerunnerjs.model.exception.command.CommandOperationException: Invalid arguments provided.
	at com.caplin.cutlass.command.testIntegration.TestIntegrationCommand.validateArguments(TestIntegrationCommand.java:151)
	at com.caplin.cutlass.command.testIntegration.TestIntegrationCommand.doCommand(TestIntegrationCommand.java:68)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:21)
	at org.bladerunnerjs.model.BRJS.runCommand(BRJS.java:354)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:35)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:27)
	at org.bladerunnerjs.model.BRJS.runUserCommand(BRJS.java:359)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:104)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:55)

org.bladerunnerjs.model.exception.command.CommandOperationException: Invalid arguments provided.
	at com.caplin.cutlass.command.testIntegration.TestIntegrationCommand.validateArguments(TestIntegrationCommand.java:151)
	at com.caplin.cutlass.command.testIntegration.TestIntegrationCommand.doCommand(TestIntegrationCommand.java:68)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:21)
	at org.bladerunnerjs.model.BRJS.runCommand(BRJS.java:354)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:35)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:27)
	at org.bladerunnerjs.model.BRJS.runUserCommand(BRJS.java:359)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:104)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:55)
```

**Comment by thecapdan** [comment]
Given this was already merged I'll move this straight to test

**Comment by thecapdan** [comment]
We now see

```
$ brjs test-integration
Problem:
  Invalid arguments provided.

Usage:
  brjs test-integration <path-to-tests>
```

Fixed
