### ISSUE TITLE
bladeset workbench CSS resource bundle throws ClassCastException DirNode can't cast to AssetContainer

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1238]
After creating an app and a bladeset, if you then restart brjs then open the bladeset workbench then it will fail to open correctly with the following error being thrown in the console:
Error in css file 'sefwsfwsf-bladeset/workbench/resources/style/workbench.css',
referencing image file 'd:\Development\brjsNew\brjs\brjs-sdk\apps\newapp\sefwsfwsf-bladeset\workbench\resources\style\br-logo.png'
        at org.bladerunnerjs.plugin.plugins.bundlers.css.TargetPathCreator.getBundleRequestForImage(TargetPathCreator.java:51)
        at org.bladerunnerjs.plugin.plugins.bundlers.css.TargetPathCreator.getRelativeBundleRequestForImage(TargetPathCreator.java:35)
        at org.bladerunnerjs.plugin.plugins.bundlers.css.CssRewriter.parseUrl(CssRewriter.java:88)

....

Caused by: java.lang.ClassCastException: org.bladerunnerjs.model.DirNode cannot be cast to org.bladerunnerjs.model.AssetContainer
        at org.bladerunnerjs.plugin.plugins.bundlers.css.TargetPathCreator.getTargetPath(TargetPathCreator.java:67)
        at org.bladerunnerjs.plugin.plugins.bundlers.css.TargetPathCreator.getBundleRequestForImage(TargetPathCreator.java:42)
        ... 66 more

**Comment by andyberry88** [comment]
I've removed the bit of code that throws this exception as part of #1085 so it should be fixed in that branch.

**Comment by andyberry88** [comment]
@thanhc What version what this seen with? I can't reproduce it in `develop` to add a failing test.

**Comment by andyberry88** [comment]
I added a test to attempt to reproduce this in eea65f4ac1390e89ae45a243409b6dc00e7e4456. Since I can't reproduce this in either develop or my branch for #1085 it looks like it's already been fixed.

**Comment by thanhc** [comment]
Verified that this no longer happens in the review-plugin-apis-1085 branch
