### ISSUE TITLE
`src-test` require paths clash with other require paths and cause an exception 

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1432]
Seen when converting some of our libs to `common-js` style. 

Having a `src-test` inside of a test pack causes the root prefix directory inside of that directory to clash with other require prefixes causing the following exception:

```
Testing libs/javascript/br-test/test-unit (UTs):
Unexpected Exception:
org.bladerunnerjs.api.model.exception.ModelOperationException: In 'br/test/ViewFixture': '../../libs/javascript/br' and '../../libs/javascript/br-test/test-unit/src-test/br' source files both available via require path 'br'.
	at org.bladerunnerjs.plugin.bundlers.commonjs.DefaultCommonJsSourceModule.getSourceModulesForRequirePaths(DefaultCommonJsSourceModule.java:189)
	at org.bladerunnerjs.plugin.bundlers.commonjs.DefaultCommonJsSourceModule.getPreExportDefineTimeDependentAssets(DefaultCommonJsSourceModule.java:123)
	at org.bladerunnerjs.plugin.bundlers.commonjs.DefaultCommonJsSourceModule.getDependentAssets(DefaultCommonJsSourceModule.java:67)
	at org.bladerunnerjs.utility.BundleSetBuilder.getModuleDependencies(BundleSetBuilder.java:161)
	at org.bladerunnerjs.utility.BundleSetBuilder.addLinkedAsset(BundleSetBuilder.java:91)
	at org.bladerunnerjs.utility.BundleSetBuilder.addSourceModule(BundleSetBuilder.java:81)
	at org.bladerunnerjs.utility.BundleSetBuilder.addLinkedAsset(BundleSetBuilder.java:104)
	at org.bladerunnerjs.utility.BundleSetBuilder.addSeedFiles(BundleSetBuilder.java:74)
	at org.bladerunnerjs.model.BundleSetCreator.createBundleSet(BundleSetCreator.java:48)
	at org.bladerunnerjs.model.AbstractBundlableNode.lambda$getBundleSet$2(AbstractBundlableNode.java:91)
	at org.bladerunnerjs.model.AbstractBundlableNode$$Lambda$1.get(Unknown Source)
	at org.bladerunnerjs.api.memoization.MemoizedValue.value(MemoizedValue.java:88)
	at org.bladerunnerjs.model.AbstractBundlableNode.getBundleSet(AbstractBundlableNode.java:90)
	at org.bladerunnerjs.legacy.command.test.testrunner.BundlerHandler.createBundleFile(BundlerHandler.java:62)
	at org.bladerunnerjs.legacy.command.test.testrunner.JsTestDriverBundleCreator.createRequiredBundles(JsTestDriverBundleCreator.java:64)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.runTest(TestRunner.java:390)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.runTestAndRecordDuration(TestRunner.java:377)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.runAllTestsInDirectory(TestRunner.java:348)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunner.runTests(TestRunner.java:164)
	at org.bladerunnerjs.legacy.command.test.testrunner.TestRunnerController.run(TestRunnerController.java:121)
	at org.bladerunnerjs.legacy.command.test.TestCommand.doCommand(TestCommand.java:54)
	at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
	at org.bladerunnerjs.api.BRJS.runCommand(BRJS.java:436)
	at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:34)
	at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:26)
	at org.bladerunnerjs.api.BRJS.runUserCommand(BRJS.java:441)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:117)
	at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:121)
	at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:70)
Caused by: org.bladerunnerjs.api.model.exception.AmbiguousRequirePathException: In 'br/test/ViewFixture': '../../libs/javascript/br' and '../../libs/javascript/br-test/test-unit/src-test/br' source files both available via require path 'br'.
	at org.bladerunnerjs.plugin.require.DefaultRequirePlugin.getAsset(DefaultRequirePlugin.java:38)
	at org.bladerunnerjs.plugin.proxy.VirtualProxyRequirePlugin.getAsset(VirtualProxyRequirePlugin.java:22)
	at org.bladerunnerjs.model.AbstractBundlableNode.getLinkedAsset(AbstractBundlableNode.java:77)
	at org.bladerunnerjs.model.AbstractBundlableNode.assets(AbstractBundlableNode.java:111)
	at org.bladerunnerjs.plugin.bundlers.commonjs.DefaultCommonJsSourceModule.getSourceModulesForRequirePaths(DefaultCommonJsSourceModule.java:185)
	... 28 more
```

**Comment by andyberry88** [comment]
Since this is blocking me from continuing on #424 I'm going to tackle this first.

**Comment by andyberry88** [comment]
After some investigation this was due to the `br` package being required, which isn't valid anyway. Closing as a non issue.
