### ISSUE TITLE
BRJS sometimes throws a NullPointerException when loading a page

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1451]
Sometimes BRJS throws a NPE when loading an aspect. Reloading the page then fixed the problem. See stacktrace below:

```
HTTP ERROR 500

Problem accessing /fxtrader/login/en_GB. Reason:

    Server Error
Caused by:

java.lang.NullPointerException
	at com.google.common.base.Joiner.join(Joiner.java:183)
	at org.bladerunnerjs.api.model.exception.CircularDependencyException.getCircularDependency(CircularDependencyException.java:41)
	at org.bladerunnerjs.api.model.exception.CircularDependencyException.<init>(CircularDependencyException.java:22)
	at org.bladerunnerjs.utility.SourceModuleDependencyOrderCalculator.getOrderedSourceModules(SourceModuleDependencyOrderCalculator.java:43)
	at org.bladerunnerjs.utility.BundleSetBuilder.createBundleSet(BundleSetBuilder.java:65)
	at org.bladerunnerjs.model.BundleSetCreator.createBundleSet(BundleSetCreator.java:50)
	at org.bladerunnerjs.model.AbstractBundlableNode.lambda$getBundleSet$2(AbstractBundlableNode.java:91)
	at org.bladerunnerjs.model.AbstractBundlableNode$$Lambda$1.get(Unknown Source)
	at org.bladerunnerjs.api.memoization.MemoizedValue.value(MemoizedValue.java:88)
	at org.bladerunnerjs.model.AbstractBundlableNode.getBundleSet(AbstractBundlableNode.java:90)
	at org.bladerunnerjs.model.AbstractBrowsableNode.filterIndexPage(AbstractBrowsableNode.java:24)
	at org.bladerunnerjs.utility.AppRequestHandler.getIndexPageContent(AppRequestHandler.java:213)
	at org.bladerunnerjs.utility.AppRequestHandler.handleLogicalRequest(AppRequestHandler.java:112)
	at org.bladerunnerjs.appserver.BRJSDevServlet.doGet(BRJSDevServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1317)
	at org.bladerunnerjs.appserver.BRJSDevServletFilter.doFilter(BRJSDevServletFilter.java:83)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:25)
	at org.bladerunnerjs.appserver.filter.BRJSHeaderFilter.doFilter(BRJSHeaderFilter.java:57)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:69)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.FileExtensionFilter.doFilter(FileExtensionFilter.java:43)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.BRJSServletFilter.doFilter(BRJSServletFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:574)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:293)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:120)
	at org.bladerunnerjs.appserver.BRJSDevServletFilter.doFilter(BRJSDevServletFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:25)
	at org.bladerunnerjs.appserver.filter.BRJSHeaderFilter.doFilter(BRJSHeaderFilter.java:57)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:69)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.FileExtensionFilter.doFilter(FileExtensionFilter.java:43)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.BRJSServletFilter.doFilter(BRJSServletFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1288)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:532)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by andyberry88** [comment]
I created this as a reminder to investigate the issue but can't reproduce it now so I'm going to close it. If I see it again I'll reopen and investigate.
