### ISSUE TITLE
Error thrown when building app with i18n token

### ISSUE THREAD

**Issue by thecapdan** [BladeRunnerJS/brjs#1462]
Only reproducible by using our it-app, and running the build-app command. WE have many apps using i18n tokens that build prefectly fine, so we need to determine what in particular is different about the it-app.

Here's the error message:

```
The app 'it-app' is either missing BRJS jar(s), contains BRJS jar(s) it shouldn't or the BRJS jar(s) are outdated. You should delete all jars prefixed with 'brjs-' in the WEB-INF/lib directory and copy in all jars contained in sdk/libs/java/application.
Error:
  org.bladerunnerjs.api.model.exception.ModelOperationException: Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.


Caused By:
  Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.


Stack Trace:
org.bladerunnerjs.api.model.exception.command.CommandOperationException: org.bladerunnerjs.api.model.exception.ModelOperationException: Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.

        at org.bladerunnerjs.plugin.commands.standard.BuildAppCommand.doCommand(BuildAppCommand.java:138)
        at org.bladerunnerjs.api.plugin.JSAPArgsParsingCommandPlugin.doCommand(JSAPArgsParsingCommandPlugin.java:79)
        at org.bladerunnerjs.plugin.proxy.VirtualProxyCommandPlugin.doCommand(VirtualProxyCommandPlugin.java:41)
        at org.bladerunnerjs.utility.CommandRunner.run(CommandRunner.java:25)
        at org.bladerunnerjs.api.BRJS.runCommand(BRJS.java:428)
        at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:34)
        at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:26)
        at org.bladerunnerjs.api.BRJS.runUserCommand(BRJS.java:433)
        at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:119)
        at org.bladerunnerjs.runner.CommandRunner.run(CommandRunner.java:123)
        at org.bladerunnerjs.runner.CommandRunner.main(CommandRunner.java:71)
Caused by: org.bladerunnerjs.api.model.exception.ModelOperationException: Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.

        at org.bladerunnerjs.api.spec.model.app.building.AppBuilderUtilis.build(AppBuilderUtilis.java:62)
        at org.bladerunnerjs.api.spec.model.app.building.StaticAppBuilder.build(StaticAppBuilder.java:17)
        at org.bladerunnerjs.api.App.build(App.java:363)
        at org.bladerunnerjs.plugin.commands.standard.BuildAppCommand.doCommand(BuildAppCommand.java:132)
        ... 10 more
Caused by: Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.

Caused by: Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.
Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.


        at org.bladerunnerjs.utility.AppRequestHandler.getIndexPageContent(AppRequestHandler.java:221)
        at org.bladerunnerjs.utility.AspectRequestHandler.getIndexPageContent(AspectRequestHandler.java:53)
        at org.bladerunnerjs.api.spec.model.app.building.AppBuilderUtilis.outputAspectIndexPage(AppBuilderUtilis.java:99)
        at org.bladerunnerjs.api.spec.model.app.building.AppBuilderUtilis.build(AppBuilderUtilis.java:53)
        ... 13 more
Caused by: org.bladerunnerjs.api.model.exception.ModelOperationException: Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.

        at org.bladerunnerjs.model.AbstractBrowsableNode.filterIndexPage(AbstractBrowsableNode.java:27)
        at org.bladerunnerjs.utility.AppRequestHandler.getIndexPageContent(AppRequestHandler.java:215)
        ... 16 more
Caused by: java.io.IOException: Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.

        at org.bladerunnerjs.plugin.bundlers.html.HTMLBundlerTagHandlerPlugin.writeTagContent(HTMLBundlerTagHandlerPlugin.java:48)
        at org.bladerunnerjs.plugin.proxy.VirtualProxyTagHandlerPlugin.writeTagContent(VirtualProxyTagHandlerPlugin.java:31)

        at org.bladerunnerjs.utility.TagPluginUtility.getTagReplacement(TagPluginUtility.java:156)
        at org.bladerunnerjs.utility.TagPluginUtility.access$100(TagPluginUtility.java:34)
        at org.bladerunnerjs.utility.TagPluginUtility$1.handleTagMatch(TagPluginUtility.java:53)
        at org.bladerunnerjs.utility.TagPluginUtility.findAndHandleTagMatches(TagPluginUtility.java:121)
        at org.bladerunnerjs.utility.TagPluginUtility.filterContent(TagPluginUtility.java:68)
        at org.bladerunnerjs.model.AbstractBrowsableNode.filterIndexPage(AbstractBrowsableNode.java:24)
        ... 17 more
Caused by: Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.

        at org.bladerunnerjs.plugin.bundlers.html.HTMLBundlerTagHandlerPlugin.translateContent(HTMLBundlerTagHandlerPlugin.java:62)
        at org.bladerunnerjs.plugin.bundlers.html.HTMLBundlerTagHandlerPlugin.writeTagContent(HTMLBundlerTagHandlerPlugin.java:45)
        ... 24 more
``` 

AC:

As a developer I want a way to know when I have missing translations in the default locale
As a developer I want my build to fail if there is no translation for the default locale
As a developer I do not want my build to fail if there is no translation for non-default locale
As a developer I'd like the build to warn me if I have missing translations for non-default locale
As an end user, I want to see text in the default locale if there is no translation in my selected locale

**Comment by andyberry88** [comment]
I've added this to the 1.1 milestone since it seems like a fairly major bug // @dchambers

**Comment by dchambers** [comment]
:+1:

**Comment by hobojed** [comment]
It seems this is because the app defines 'de' as a language, but has no de.properties files.
I added a de.properties file that defined the specific i18n token that the error was complaining about, and the app built. Not sure yet why only that i18n token was required, and the others could remain undefined (perhaps the others are unused by the app).

**Comment by thecapdan** [comment]
@hobojed @andyberry88 great, appears to be a low priority bug then. potential actions:

1. improve error message so it tells us which language is missing the translation
and/or
2. allow apps to be built with missing translations

**Comment by hobojed** [comment]
After further investigation, I realised that this issue occurs when a missing token (for any locale) is referenced in an HTML template.

I spoke to @andyberry88  and we decided to improve the error message so that it informs what locale the token was missing for, and that we should also consider making JS calls to i18n throw errors for missing tokens to be more consistent with how it works in HTML templates.

**Comment by hobojed** [comment]
Created PR for this: https://github.com/BladeRunnerJS/brjs/pull/1505

**Comment by hobojed** [comment]
As discussed with @andyberry88, @dchambers and @thecapdan, the following are the desired behaviours when an i18n token is missing:

 | In Dev | In Prod
--------------|------------ | -------------
**In HTML** | Replace with ???&nbsp;token.name&nbsp;??? | Replace with default language and log warning. If token is also missing for default language, build should throw error
**In JS** | Return "???&nbsp;token.name&nbsp;???" | Return default language and log warning to fell. If token is also missing for default language, throw JS error

**Comment by dchambers** [comment]
That's exactly it :+1:

**Comment by hobojed** [comment]
Following the discussion this morning (with @thecapdan, @andyberry88 and @dchambers) the Acceptance Criteria for missing i18n tokens are as follows:

1. As a developer I want a way to know when I have missing translations in the default locale
2. As a developer I want my build to fail if there is no translation for the default locale
3. As a developer I do not want my build to fail if there is no translation for non-default locale
4. As a developer I'd like the build to warn me if I have missing translations for non-default locale
5. As an end user, I want to see text in the default locale if there is no translation in my selected locale

As such, the current desired behaviours are:

 | In Dev | In Prod
--------------|------------ | -------------
**In HTML** | Replace with ???&nbsp;token.name&nbsp;???. If token is also missing for default language, build should throw error | Replace with default language and log warning. If token is also missing for default language, build should throw error
**In JS** | Return "???&nbsp;token.name&nbsp;???". If token is also missing for default language, throw JS error | Return default language and log warning to fell. If token is also missing for default language, throw JS error

It was also decided that a further improvement would be to have dev work exactly like prod, but to have a tool that would highlight all untranslated keys.

**Comment by dchambers** [comment]
:+1:

**Comment by hobojed** [comment]
Implementing this has created a backwards compatibility issue for tests. They will now need to load the i18n bundle if they test any code that uses i18n tokens. Previously this wasn't a requirement.

**Comment by hobojed** [comment]
In making this change, I also found two CT i18n tokens that were being used by BRJS (in br/validation/ISODateValidator):

ct.presenter.validator.invalidISODateFormat
ct.presenter.validator.valueNullUndefinedOrEmptyString

These both have BRJS equivalents that aren't being used, so I suspect it was an oversight when transferring the class from CT to BRJS.

I have corrected this, but it will be another potential backwards compatibility issue (for anyone who has overridden or translated either of those key. Customers will need to change:

**Comment by andyberry88** [comment]
https://github.com/BladeRunnerJS/brjs/pull/1505 is the PR for this.

**Comment by thecapdan** [comment]
while testing this branch I found that the dashboard no longer loaded because of the following error:

```
Uncaught Error: InvalidParametersError: Unable to find a replacement for the i18n key "br.presenter.validator.invalidselection"
```

The reason was because the dashboard index file didn't have an i18n bundle tag. So, apps that use a library that use locales will now have to have an i18n bundle to work (whereas previously they were able to survive without in dev)

I can solve this issue by adding the tag to the index page

**Comment by thecapdan** [comment]
@hobojed can we add some nice release notes for this in Latest.md. thanks

**Comment by andyberry88** [comment]
Release notes added to #1564.
