### ISSUE TITLE
[bug] BRJS watches irrelevant folders for changes

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1507]
I saw this exception in my console when running `brjs serve`.

```
Exception in thread "WatchingFileModificationObserverThread" java.lang.RuntimeException: java.nio.file.NoSuchFileException: /Users/janh/dev/salestrader/.git/rebase-apply/rewritten
	at org.bladerunnerjs.memoization.WatchingFileModificationObserverThread.run(WatchingFileModificationObserverThread.java:59)
Caused by: java.nio.file.NoSuchFileException: /Users/janh/dev/salestrader/.git/rebase-apply/rewritten
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.getLastModifiedTime(Files.java:2266)
	at sun.nio.fs.PollingWatchService$PollingWatchKey.<init>(PollingWatchService.java:260)
	at sun.nio.fs.PollingWatchService.doPrivilegedRegister(PollingWatchService.java:165)
	at sun.nio.fs.PollingWatchService.access$000(PollingWatchService.java:45)
	at sun.nio.fs.PollingWatchService$2.run(PollingWatchService.java:128)
	at sun.nio.fs.PollingWatchService$2.run(PollingWatchService.java:125)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.PollingWatchService.register(PollingWatchService.java:124)
	at sun.nio.fs.UnixPath.register(UnixPath.java:897)
	at org.bladerunnerjs.memoization.MacHighSensitivityWatchKeyService.createWatchKeyForDir(MacHighSensitivityWatchKeyService.java:26)
	at org.bladerunnerjs.memoization.DefaultWatchKeyService.createWatchKeysForDir(DefaultWatchKeyService.java:33)
	at org.bladerunnerjs.memoization.WatchingFileModificationObserverThread.pollWatchKeyForEvents(WatchingFileModificationObserverThread.java:123)
	at org.bladerunnerjs.memoization.WatchingFileModificationObserverThread.checkForUpdates(WatchingFileModificationObserverThread.java:83)
	at org.bladerunnerjs.memoization.WatchingFileModificationObserverThread.run(WatchingFileModificationObserverThread.java:54)
```

Seems like BRJS is also watching the `.git` folder for changes, which is unnecessary. I'm assuming BRJS watches my whole repository, which seems inefficient. Why don't we change the watcher to only watch the following locations:

```
apps/
conf/
js-patches/
sdk/libs/javascript
```

These are the only possible root locations where things that my app needs can be. I suspect this will give as a performance boost, or at the least, prevent exceptions like above from happening.

**Comment by dchambers** [comment]
@andyberry88, do you think this is an easy fix or not? It sounds like it should be easy, and I think it might help improve the start-up time on Windows for large code-bases?

**Comment by andyberry88** [comment]
Definitely something we should do, I don't think it'll be trivial but shouldn't be massively complicated though. We'll just need to make sure we watch all important directories since it could very easily mess with `MemoizedFile`s since they're now used throughout the model rather than in areas that improve performance the most. We'll also need a mechanism that'll fail fast if directories exist next to the SDK that we maybe should be watching.

**Comment by dchambers** [comment]
Not quite sure I understand all of that. Let's talk about it after tomorrows stand-up.

**Comment by andyberry88** [comment]
:+1:  In a nut shell: yes we should do it, possibly ASAP. We just need to make sure it doesn't allow us to introduce bugs around memoized values as we change things in the future.
