### ISSUE TITLE
IllegalArgumentException when requiring non existent class

### ISSUE THREAD

**Issue by thecapdan** [BladeRunnerJS/brjs#1786]
To reproduce. 

require('NonExistentClass');

... and load the app.

```
HTTP ERROR 500

Problem accessing /fxtrader/en_GB. Reason:

    Server Error
Caused by:

javax.servlet.ServletException: java.lang.IllegalArgumentException: setContentLength(0) when already written 743
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:96)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.FileExtensionFilter.doFilter(FileExtensionFilter.java:38)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.BRJSServletFilter.doFilter(BRJSServletFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: setContentLength(0) when already written 743
	at org.eclipse.jetty.server.Response.setContentLength(Response.java:912)
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:86)
	... 34 more
```

**Comment by thecapdan** [comment]
I believe this issue should be fixed by https://github.com/BladeRunnerJS/brjs/pull/1788

What a joyful coincidence. It's a Christmas miracle (in June)

![miracle](https://user-images.githubusercontent.com/6085260/27530188-77469a74-5a4f-11e7-83ac-58bbbb607ee1.gif)
