### ISSUE TITLE
BRJS broken with OSX High Sierra

### ISSUE THREAD

**Issue by AndyLyons** [BladeRunnerJS/brjs#1796]
The recent file system changes in OSX High Sierra seem to have broken BRJS. When you try and load the BRJS app in the browser you see the following 500 error:
```
java.lang.RuntimeException: Require paths for the asset 'blades/motfblotter/resources/xml/clientGridDefinitions.xml' cannot be registered. An asset for the require path 'caplinx/motfblotter/client/execution-base' has already been registered.
	at org.bladerunnerjs.api.plugin.DefaultAssetRegistry.registerAsset(DefaultAssetRegistry.java:51)
	at org.bladerunnerjs.api.plugin.DefaultAssetRegistry.registerSeedAsset(DefaultAssetRegistry.java:30)
	at org.bladerunnerjs.plugin.bundlers.xml.XMLAssetPlugin.discoverAssets(XMLAssetPlugin.java:44)
	at org.bladerunnerjs.plugin.proxy.VirtualProxyAssetPlugin.discoverAssets(VirtualProxyAssetPlugin.java:25)
	at org.bladerunnerjs.api.plugin.DefaultAssetRegistry.discoverFurtherAssets(DefaultAssetRegistry.java:98)
	at org.bladerunnerjs.plugin.brjsconformant.BRJSConformantAssetPlugin.discoverFurtherAssetsForChild(BRJSConformantAssetPlugin.java:198)
	at org.bladerunnerjs.plugin.brjsconformant.BRJSConformantAssetPlugin.createAssetsForChildDir(BRJSConformantAssetPlugin.java:180)
	at org.bladerunnerjs.plugin.brjsconformant.BRJSConformantAssetPlugin.discoverFurtherAssetsForChild(BRJSConformantAssetPlugin.java:211)
	at org.bladerunnerjs.plugin.brjsconformant.BRJSConformantAssetPlugin.createAssetsForChildDir(BRJSConformantAssetPlugin.java:180)
	at org.bladerunnerjs.plugin.brjsconformant.BRJSConformantAssetPlugin.discoverAssets(BRJSConformantAssetPlugin.java:57)
	at org.bladerunnerjs.plugin.proxy.VirtualProxyAssetPlugin.discoverAssets(VirtualProxyAssetPlugin.java:25)
	at org.bladerunnerjs.api.plugin.DefaultAssetRegistry.discoverFurtherAssets(DefaultAssetRegistry.java:98)
	at org.bladerunnerjs.model.AbstractAssetContainer.lambda$assetDiscoveryResult$0(AbstractAssetContainer.java:104)
	at org.bladerunnerjs.api.memoization.MemoizedValue.value(MemoizedValue.java:88)
	at org.bladerunnerjs.model.AbstractAssetContainer.assetDiscoveryResult(AbstractAssetContainer.java:102)
	at org.bladerunnerjs.model.AbstractAssetContainer.asset(AbstractAssetContainer.java:56)
	at org.bladerunnerjs.plugin.require.DefaultRequirePlugin.getAsset(DefaultRequirePlugin.java:30)
	at org.bladerunnerjs.plugin.proxy.VirtualProxyRequirePlugin.getAsset(VirtualProxyRequirePlugin.java:22)
	at org.bladerunnerjs.model.AbstractBundlableNode.getLinkedAsset(AbstractBundlableNode.java:92)
	at org.bladerunnerjs.plugin.require.ServiceCommonJsSourceModule.getPreExportDefineTimeDependentAssets(ServiceCommonJsSourceModule.java:93)
	at org.bladerunnerjs.plugin.require.ServiceCommonJsSourceModule.getDependentAssets(ServiceCommonJsSourceModule.java:37)
	at org.bladerunnerjs.utility.BundleSetBuilder.getModuleDependencies(BundleSetBuilder.java:163)
	at org.bladerunnerjs.utility.BundleSetBuilder.addLinkedAsset(BundleSetBuilder.java:95)
	at org.bladerunnerjs.utility.BundleSetBuilder.addSourceModule(BundleSetBuilder.java:84)
	at org.bladerunnerjs.utility.BundleSetBuilder.addLinkedAsset(BundleSetBuilder.java:109)
	at org.bladerunnerjs.utility.BundleSetBuilder.addSeedFiles(BundleSetBuilder.java:77)
	at org.bladerunnerjs.model.BundleSetCreator.createBundleSet(BundleSetCreator.java:48)
	at org.bladerunnerjs.model.AbstractBundlableNode.lambda$getBundleSet$0(AbstractBundlableNode.java:106)
	at org.bladerunnerjs.api.memoization.MemoizedValue.value(MemoizedValue.java:88)
	at org.bladerunnerjs.model.AbstractBundlableNode.getBundleSet(AbstractBundlableNode.java:105)
	at org.bladerunnerjs.utility.AppRequestHandler.getLocaleForwardingPageJSBundleContent(AppRequestHandler.java:289)
	at org.bladerunnerjs.utility.AppRequestHandler.getLocaleForwardingPageContent(AppRequestHandler.java:275)
	at org.bladerunnerjs.utility.AppRequestHandler.handleLogicalRequest(AppRequestHandler.java:112)
	at org.bladerunnerjs.appserver.BRJSDevServlet.doGet(BRJSDevServlet.java:85)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.bladerunnerjs.appserver.BRJSDevServletFilter.doFilter(BRJSDevServletFilter.java:83)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:25)
	at org.bladerunnerjs.appserver.filter.BRJSHeaderFilter.doFilter(BRJSHeaderFilter.java:57)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:109)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.FileExtensionFilter.doFilter(FileExtensionFilter.java:38)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.BRJSServletFilter.doFilter(BRJSServletFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:203)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73)
	at org.bladerunnerjs.appserver.BRJSDevServletFilter.doFilter(BRJSDevServletFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:25)
	at org.bladerunnerjs.appserver.filter.BRJSHeaderFilter.doFilter(BRJSHeaderFilter.java:57)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.TokenisingServletFilter.doFilter(TokenisingServletFilter.java:69)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.filter.FileExtensionFilter.doFilter(FileExtensionFilter.java:41)
	at org.bladerunnerjs.appserver.util.VirtualFilterChain.doFilter(VirtualFilterChain.java:30)
	at org.bladerunnerjs.appserver.BRJSServletFilter.doFilter(BRJSServletFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:745)
```

The `./brjs app-deps <appname>` command will also reproduce the error.

**Comment by AndyLyons** [comment]
Closing for now, it seems to be caused by some BRJS plugins and I'll investigate there instead.
